import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 13

[font.normal]
family = "Iosevka"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
