tap 'caskroom/cask'
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'neovim/neovim'
tap 'caskroom/fonts'

# basic utils
brew 'coreutils'
brew 'findutils', args: ['with-default-names']
brew 'diffutils', args: ['with-default-names']
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'readline'
brew 'grep', args: ['with-default-names']
brew 'gawk'
brew 'less', args: ['with-default-names']
brew 'wget'
brew 'xz'
brew 'ack'
brew 'tree'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'colordiff'

# toolbox
brew 'fish'
brew 'git'
brew 'stow'
brew 'the_silver_searcher'
brew 'tmux'
brew 'httpie'
brew 'neovim'
brew 'cloc'

# js development
brew 'node@8'

# gui apps
brew 'cask'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'karabiner-elements'
cask 'spectacle'
cask 'slack'
cask 'spotify'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'android-file-transfer'
cask 'tunnelblick'
cask 'keepassxc'
cask 'mpv'

# fonts
cask 'font-iosevka'
cask 'font-lato'
cask 'font-material-icons'
