# Run 'codeconf' to generate settings.json from this file
---
breadcrumbs.symbolPath: 'off'
debug.openDebug: neverOpen
debug.toolBarLocation: docked
cSpell.enabled: false
cSpell.showStatus: false
editor.fontFamily: Iosevka Term
editor.fontSize: 16
editor.gotoLocation.multipleDeclarations: goto
editor.gotoLocation.multipleDefinitions: goto
editor.gotoLocation.multipleImplementations: goto
editor.gotoLocation.multipleTypeDefinitions: goto
editor.hideCursorInOverviewRuler: true
editor.lineNumbers: relative
editor.minimap.enabled: false
editor.renderWhitespace: boundary
editor.rulers:
- 80
editor.scrollbar.horizontal: hidden
editor.suggestSelection: first
explorer.openEditors.visible: 0
extensions.ignoreRecommendations: true
files.associations:
  '*.vim': vimrc
files.enableTrash: false
files.hotExit: onExitAndWindowClose
files.insertFinalNewline: true
files.simpleDialog.enable: true
git.autoStash: true
git.fetchOnPull: true
rest-client.enableTelemetry: false
rest-client.previewResponseInUntitledDocument: true
search.collapseResults: alwaysExpand
search.mode: reuseEditor
search.quickOpen.includeHistory: false
search.searchEditor.reusePriorSearchConfiguration: true
search.smartCase: true
task.problemMatchers.neverPrompt:
  shell: true
telemetry.enableTelemetry: false
terminal.integrated.fontSize: 16
terminal.integrated.scrollback: 10000
vim.highlightedyank.enable: true
vim.hlsearch: true
vim.leader: '<space>'
vim.useSystemClipboard: true
vim.visualstar: true
whichkey.delay: 400
whichkey.sortOrder: alphabetically
window.enableMenuBarMnemonics: false
window.menuBarVisibility: hidden
window.restoreWindows: none
window.dialogStyle: custom
workbench.activityBar.visible: false
workbench.colorCustomizations:
  statusBar.background: "#1a1a1a"
  statusBar.noFolderBackground: "#1a1a1a"
  statusBar.debuggingBackground: "#943131"
workbench.editor.enablePreviewFromCodeNavigation: true
workbench.editor.restoreViewState: false
workbench.editor.showIcons: false
workbench.editor.showTabs: false
workbench.editor.untitled.hint: hidden
workbench.enableExperiments: false
workbench.iconTheme: vs-minimal
workbench.list.automaticKeyboardNavigation: false
workbench.panel.opensMaximized: never
workbench.panel.defaultLocation: right
workbench.settings.editor: json
workbench.settings.enableNaturalLanguageSearch: false
workbench.sideBar.location: right
workbench.startupEditor: newUntitledFile
workbench.tips.enabled: false
'[java]':
  editor.rulers:
  - 100
  - 120
'[python]':
  editor.rulers:
  - 88
