# Run 'codeconf' to generate settings.json from this file
---
breadcrumbs.symbolPath: 'off'
debug.openDebug: openOnDebugBreak
debug.toolBarLocation: docked
editor.fontFamily: Iosevka Term
editor.fontSize: 16
editor.gotoLocation.multipleDeclarations: "goto"
editor.gotoLocation.multipleDefinitions: "goto"
editor.gotoLocation.multipleImplementations: "goto"
editor.gotoLocation.multipleTypeDefinitions: "goto"
editor.hideCursorInOverviewRuler: true
editor.lineNumbers: relative
editor.minimap.enabled: false
editor.renderWhitespace: boundary
editor.rulers:
- 80
editor.suggestSelection: first
explorer.openEditors.visible: 0
extensions.ignoreRecommendations: true
files.associations:
  "*.vim": vimrc
files.enableTrash: false
files.hotExit: onExitAndWindowClose
files.insertFinalNewline: true
files.simpleDialog.enable: true
fileutils.typeahead.enabled: false
git.autoStash: true
git.fetchOnPull: true
search.collapseResults: alwaysExpand
search.quickOpen.includeHistory: false
search.searchEditor.reusePriorSearchConfiguration: true
search.smartCase: true
task.problemMatchers.neverPrompt:
  shell: true
telemetry.enableTelemetry: false
terminal.integrated.fontSize: 16
terminal.integrated.scrollback: 10000
vim.hlsearch: true
vim.leader: "<space>"
vim.useSystemClipboard: true
vim.visualstar: true
window.enableMenuBarMnemonics: false
window.menuBarVisibility: hidden
window.restoreWindows: none
workbench.activityBar.visible: false
workbench.colorTheme: Dracula
workbench.editor.enablePreviewFromQuickOpen: false
workbench.editor.restoreViewState: false
workbench.editor.showIcons: false
workbench.editor.showTabs: false
workbench.iconTheme: vs-minimal
workbench.list.automaticKeyboardNavigation: false
workbench.settings.editor: json
workbench.settings.enableNaturalLanguageSearch: false
workbench.startupEditor: newUntitledFile
workbench.tips.enabled: false
"[java]":
  editor.rulers:
  - 100
  - 120
