# Run 'codeconf' to generate settings.json from this file
---
breadcrumbs.symbolPath: 'off'
debug.openDebug: neverOpen
debug.toolBarLocation: docked
editor.bracketPairColorization.enabled: true
editor.fontFamily: Iosevka
editor.fontSize: 16
editor.gotoLocation.multipleDeclarations: goto
editor.gotoLocation.multipleDefinitions: goto
editor.gotoLocation.multipleImplementations: goto
editor.gotoLocation.multipleTypeDefinitions: goto
editor.guides.bracketPairs: true
editor.hideCursorInOverviewRuler: true
editor.lineNumbers: relative
editor.minimap.enabled: false
editor.renderWhitespace: boundary
editor.rulers:
- 80
editor.scrollbar.horizontal: hidden
editor.stickyScroll.enabled: false
editor.suggestSelection: first
explorer.compactFolders: false
extensions.ignoreRecommendations: true
files.associations:
  '*.vim': vimrc
files.enableTrash: false
files.hotExit: onExitAndWindowClose
files.insertFinalNewline: true
files.simpleDialog.enable: true
git.autoStash: true
git.fetchOnPull: true
rest-client.enableTelemetry: false
rest-client.previewColumn: current
search.collapseResults: alwaysCollapse
search.quickOpen.includeHistory: false
search.searchEditor.reusePriorSearchConfiguration: true
search.smartCase: true
task.autoDetect: 'off'
task.problemMatchers.neverPrompt:
  shell: true
telemetry.telemetryLevel: 'off'
terminal.integrated.defaultProfile.linux: "toolbox"
terminal.integrated.fontSize: 16
terminal.integrated.tabs.enabled: false
terminal.integrated.profiles.linux:
  # flatpak-spawn --host distrobox enter distrobox-sid -e nvim
  toolbox:
    path: "flatpak-spawn"
    args:
    - "--host"
    - "--env=TERM=xterm-256color"
    - "distrobox"
    - "enter"
    - "distrobox-sid"
terminal.integrated.scrollback: 10000
vim.highlightedyank.enable: true
vim.hlsearch: true
vim.leader: '<space>'
vim.useSystemClipboard: true
vim.visualstar: true
whichkey.delay: 400
whichkey.sortOrder: alphabetically
window.commandCenter: false
window.dialogStyle: custom
window.enableMenuBarMnemonics: false
window.menuBarVisibility: hidden
window.restoreWindows: none
window.titleBarStyle: custom # until they allow to disable the titlebar
workbench.activityBar.location: hidden
workbench.editor.empty.hint: hidden
workbench.editor.enablePreviewFromCodeNavigation: true
workbench.editor.enablePreviewFromQuickOpen: true
workbench.editor.restoreViewState: false
workbench.editor.sharedViewState: true
workbench.editor.showIcons: false
workbench.editor.showTabs: none
workbench.enableExperiments: false
workbench.iconTheme: vs-minimal
workbench.layoutControl.enabled: false
workbench.panel.defaultLocation: right
workbench.panel.opensMaximized: never
workbench.settings.editor: json
workbench.settings.enableNaturalLanguageSearch: false
workbench.sideBar.location: right
workbench.startupEditor: none
workbench.tips.enabled: false
'[java]':
  editor.rulers:
  - 100
  - 120
'[python]':
  editor.rulers:
  - 88
